name: Load new jobs oportunities

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm start
        mkdir build
        mv data.json build
      env:
        REPOSITORIES: 'frontendbr/vagas,backend-br/vagas'

    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.4.1
      with:
        target_branch: gh-pages
        build_dir: build
      env:
        GITHUB_TOKEN: ${{ secrets.FAKEAPI_PAGES_TOKEN }}
